MusikMediaPlayer/Controllers/AlbumController.cs
using Nwd.BackOffice.Impl;
using Nwd.BackOffice.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusikMediaPlayer.Controllers
{
    public class AlbumController : Controller
    {
        [SuperAuthorize]
        [HttpGet]
        public ActionResult List()
        {
            var listAlbum = new AlbumRepository().GetAllAlbums();

            return View(listAlbum);
        }

        [SuperAuthorize]
        [HttpGet]
        public ActionResult Create()
        {
            var album = new Album { Artist = new Artist() };
            ViewBag.TrackNumber = album.Tracks.Count;
            return View(album);
        }

        [SuperAuthorize]
        [HttpPost]
        public ActionResult Create(Album album)
        {
            if (!IsValidAlbum(album))
                return View(album);

            var createdAlbum = new AlbumRepository().CreateAlbum(album, this.Server);
            return RedirectToAction("Details", new { createdAlbum.Id });
        }

        [SuperAuthorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var album = new AlbumRepository().GetAlbumForEdit(id);
            ViewBag.TrackNumber = album.Tracks.Count;
            return View(album);
        }

        [SuperAuthorize]
        [HttpPost]
        public ActionResult Edit(Album album)
        {
            if(!IsValidAlbum(album))
                return View(album);

            new AlbumRepository().EditAlbum(this.Server, album);
            return RedirectToAction("Details", new { album.Id });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var album = new AlbumRepository().GetAlbumForEdit(id);
          
            return View(album);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            new AlbumRepository().DeleteAlbum(id);

            return RedirectToAction("List");
        }

        [Authorize]
        public PartialViewResult BlankEditorTrack(int index)
        {
            ViewBag.TrackNumber = index;
            return PartialView("_CreateTrack", new Track());
        }

        private bool IsValidAlbum(Album album)
        {
            if (album.CoverImagePath == null)
            {
                if (!(album.CoverFile.ContentLength > 0))
                {
                    ViewBag.Error = "L'image n'éxiste pas";
                    return false;
                }
            }

            if (album.Tracks == null)
                return true;

            foreach (var track in album.Tracks)
            {
                if (track.FileRelativePath != null)
                    continue;

                if (!(track.File.ContentLength > 0))
                {
                    ViewBag.Error = "Un track n'éxiste pas";
                    return false;
                }
            }

            return true;
        }
	}
}

MusikMediaPlayer/Views/Album/Create.cshtml
@model Nwd.BackOffice.Model.Album
@{
    ViewBag.Title = "Create";
}

<h2>Create a new album</h2>

@using (Html.BeginForm("Create", "Album", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary()
    <p class="error">@ViewBag.Error</p>
    
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Artist</p>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Artist.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Artist.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Type, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Type, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Duration, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Duration)
            @Html.ValidationMessageFor(model => model.Duration)
        </div>
    </div>
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Release Date</p>
        <div class="col-md-10">
            @Html.EditorFor(m => m.ReleaseDate)
            @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>
    </div>
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Album Cover</p>
        <div class="col-md-10">
            <input type="file" name="CoverFile" id="CoverFile" />
        </div>
    </div>
    <div id="editorTrack">
        @foreach(var track in Model.Tracks)
        {
            Html.RenderPartial("_CreateTrack", track);
        }
    </div>
   <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Add another...", "BlankEditorTrack", null, new { id = "addTrack" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">

        var count = @ViewBag.TrackNumber;

        $("#addTrack").click(function () {

            $.ajax({
                url: this.href,
                data: { index: (count ++)},
                cache: false,
                success: function (html) { $("#editorTrack").append(html); }
            });
            return false;
        });
    </script>
}

MusikMediaPlayer/Views/Album/Details.cshtml
@model Nwd.BackOffice.Model.Album

@{
    ViewBag.Title = "Details de l'album";
}

<h2>Album</h2>

<div>
    <p> @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) | @Html.ActionLink("Delete", "Delete", new { id = Model.Id })</p>  
	
    <table>
        <tr>
            <td>
                <img src=@Html.DisplayFor(model => model.CoverImagePath) width="120" height="120" />
            </td>
            <td> 
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Duration)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Duration)
                    </dd>

                    <dt>
                        Release Date
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ReleaseDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Type)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Type)
                    </dd>

                    <dt>
                        Artist
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Artist.Name)
                    </dd>

                </dl>
            </td>          
        </tr>                
    </table>
 
    

    <hr />
    <h4>TrackList</h4> 
    
    <table class="table">
        @foreach(var item in Model.Tracks)
        {
            <tr>
                <th>
                    Id
                </th>
                <th>
                    @Html.DisplayNameFor(modelItem => item.Song.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItem => item.Duration)
                </th>
            </tr>

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Song_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Song.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>         
            </tr>
        }
    </table>

</div>
<p> @Html.ActionLink("Back to the list", "List") </p>

MusikMediaPlayer/Views/Album/Edit.cshtml
@model Nwd.BackOffice.Model.Album
@{
    ViewBag.Title = "Edit";
}

<h2>Edit an album.</h2>

@using (Html.BeginForm("Edit", "Album", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.CoverImagePath);
    
    @Html.ValidationSummary()
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Artist</p>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Artist.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Artist.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Type, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Type, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Duration, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Duration)
            @Html.ValidationMessageFor(model => model.Duration)
        </div>
    </div>
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Release Date</p>
        <div class="col-md-10">
            @Html.EditorFor(m => m.ReleaseDate)
            @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>
    </div>
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Album Cover</p>
        <div class="col-md-10">
            <input type="file" name="CoverFile" id="CoverFile" />
        </div>
    </div>
    <div id="editorTrack">
        @foreach (var track in Model.Tracks)
        {
            Html.RenderPartial("_CreateTrack", track);
        }
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Add another...", "BlankEditorTrack", null, new { id = "addTrack" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Valid" />
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">

        var count = @ViewBag.TrackNumber;

        $("#addTrack").click(function () {

            $.ajax({
                url: this.href,
                data: { index: (count ++)},
                cache: false,
                success: function (html) { $("#editorTrack").append(html); }
            });
            return false;
        });
    </script>
}

MusikMediaPlayer/Views/Album/List.cshtml
@model IEnumerable<Nwd.BackOffice.Model.Album>

@{
    ViewBag.Title = "Albums List";
}
<hr />
<h2>Albums list</h2>

<p>
    @Html.ActionLink("Create an album", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            Release Date
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            Album Cover
        </th>
        <th>
            Artist
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            <img src=@Html.DisplayFor(modelItem => item.CoverImagePath) width="100" height="100" />
        </td>
        
        <td>
             @Html.DisplayFor(modelItem => item.Artist.Name)
           
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) 
        </td>
    </tr>
}

</table>

MusikMediaPlayer/Views/Album/_CreateTrack.cshtml
@model Nwd.BackOffice.Model.Track

@{
    string prefixe = "Tracks[" + ViewBag.TrackNumber + "]";
    string prefixeFile = prefixe + ".File";
    ViewBag.TrackNumber = ViewBag.TrackNumber + 1;
}

<hr />
<div class="form-group">
    <p class="col-md-2 control-label" style="font-weight:bold;">Song Title</p>
    <div class="col-md-10">
        @{Html.ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix = prefixe;}
        @Html.TextBoxFor(m => m.Song.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Song.Name)
    </div>
</div>
   <div class="form-group">
       <p class="col-md-2 control-label" style="font-weight:bold;">Song Duration</p>
       <div class="col-md-10">
           @{Html.ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix = prefixe;}
           @Html.TextBoxFor(m => m.Duration, new { @class = "form-control" })
           @Html.ValidationMessageFor(model => model.Duration)
       </div>
</div>
    <div class="form-group">
        <p class="col-md-2 control-label" style="font-weight:bold;">Song File</p>
        <div class="col-md-10">
            <input type="file" name="@prefixeFile" id="File" style="margin-top:5px" />
        </div>
</div>